version: '3.8'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./index.js:/app/index.js
      - ./public/:/app/public/
      - ./logs:/app/logs
    ports:
      - "3000:3000"